INSERT INTO AUTHORS (ID, NAME) VALUES
  (1, 'Gupta'),
  (2, 'Vu'),
  (3, 'America');
  
INSERT INTO BOOKS (ID, NAME, NUMBERPAGES, AUTHOR_ID) VALUES
  (1, 'A VOLTA DOS QUE NÃO FORAM',200, 1),
  (2, 'POEIRA EM ALTO MAR',300, 2),
  (3, 'O CORONA VIRUS',400, 3);